//
//  MainPresenter.swift
//  ForeignExchangeRates
//
//  Created Titipan Sakunwongsalee on 16/9/2562 BE.
//  Copyright © 2562 Titipan Sakunwongsalee. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPresenter: MainPresenterProtocol {

    weak private var view: MainViewProtocol?
    var interactor: MainInteractorInputProtocol?
    private let router: MainWireframeProtocol

    init(interface: MainViewProtocol, interactor: MainInteractorInputProtocol?, router: MainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func showConvertView(model: [ExchangeRatesModel]) {
        router.goToConvertView(model: model)
    }
    
    func getExchangeRates() {
        interactor?.callApiExchangeRates()
    }
}

extension MainPresenter: MainInteractorOutputProtocol {
    func callApiExchangeRatesSuccess(model: [ExchangeRatesModel]) {
        view?.showListExchangeRates(model: model)
    }
}
