//
//  MainProtocols.swift
//  ForeignExchangeRates
//
//  Created Titipan Sakunwongsalee on 16/9/2562 BE.
//  Copyright © 2562 Titipan Sakunwongsalee. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainPresenterProtocol: class {

    var interactor: MainInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MainInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MainInteractorInputProtocol: class {

    var presenter: MainInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MainViewProtocol: class {

    var presenter: MainPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
