//
//  ConvertCurrencyInteractor.swift
//  ForeignExchangeRates
//
//  Created Titipan Sakunwongsalee on 17/9/2562 BE.
//  Copyright © 2562 Titipan Sakunwongsalee. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConvertCurrencyInteractor: ConvertCurrencyInteractorInputProtocol {

    weak var presenter: ConvertCurrencyInteractorOutputProtocol?
}
