//
//  ConvertCurrencyRouter.swift
//  ForeignExchangeRates
//
//  Created Titipan Sakunwongsalee on 17/9/2562 BE.
//  Copyright © 2562 Titipan Sakunwongsalee. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConvertCurrencyRouter: ConvertCurrencyWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(model: [ExchangeRatesModel]) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ConvertCurrencyViewController(nibName: nil, bundle: nil)
        let interactor = ConvertCurrencyInteractor()
        let router = ConvertCurrencyRouter()
        let presenter = ConvertCurrencyPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.listRate = model

        return view
    }
}
